FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy rest of the app
COPY . .

ENV CHOKIDAR_USEPOLLING=true
EXPOSE 3000

# Reemplaza la proxy en package.json por http://api:4000 (resoluble en Docker) y arranca CRA
CMD ["sh", "-c", "sed -i 's|\"proxy\": \"http://localhost:4000\"|\"proxy\": \"http://api:4000\"|' package.json && npm start"]
